<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Title>Blazorify Flux</Title>
    <Description>Blazorify.Flux is a Flux architecture implementation for Blazor, providing a structured and predictable approach to state management using unidirectional data flow.</Description>
    <PackageTags>blazor; flux; redux;</PackageTags>
    <PackageProjectUrl>https://github.com/blazorify/flux</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <RepositoryUrl>https://github.com/blazorify/flux</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>1.0.0</Version>
    <Authors>lambidu</Authors>
    <Company>Blazorify</Company>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>1701;1702;IDE0058</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Blazorify.Flux.Tests.Unit" />
    <InternalsVisibleTo Include="Blazorify.Flux.Tests.Integration" />
    <InternalsVisibleTo Include="Blazorify.Flux.Tests.Components" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>